- hosts: centos
  become: yes
  vars_files:
    - varfile
  tasks:
    
    - name: install httpd
      yum:
        name: "{{pack1}}"
        state: installed
    
    - name: install httpd
      yum:
        name: "{{extract}}"
        state: installed

    - name: start httpd service
      service:
        name: "{{pack1}}"
        state: started 
   
    - name: download sample html file
      get_url:        
        url: "{{cssurl}}"
        dest: "{{remote_dest}}"

    
    - name: unzip rocket-internet.zip
      unarchive:
        src: /home/ansadm/rocket-internet.zip
        dest: /var/www/html/ 
        remote_src: yes 
